### ISSUE TITLE
1-Wire Sensoren zeigen in VenusOS keine - Temperaturen an 

### ISSUE THREAD

**Issue by T-Minberg** [Rikkert-RS/VenusOS-TemperatureService#10]
Ich habe auf meinem VenusOS zwei 1-Wire Temperatursensoren angeschlossen. Die Sensoren funktionieren bei Plusgraden normal. Wenn aber der Temperaturbereich in Minus geht, zeigen die Sensoren nur noch OK an. Was kann man ändern oder sind die Sensoren def.?
Danke schon mal für Antworten.

**Comment by Julesmr** [comment]
Ich habe das gleiche problem.  Hast du eine Lösung gefunden?

**Comment by T-Minberg** [comment]
Nein, habe noch keine Lösung.
Ich hoffe das jemand das Problem lösen kann

**Comment by Rikkert-RS** [comment]
Moin Leute, ich habe leider gerade wenig Zeit hier was nachzuschauen im Code. Ich werde mir das aber anschauen, muss dann selber aber erstmal nen Testaufbau haben. Denke am WE komme ich endlich mal wieder dazu in dem Bereich was zu tun. 

Mfg Rickert-RS

**Comment by Rikkert-RS** [comment]
Hello everyone,

Ich denke das ich mit Version 0.51 das Problem mit den nicht angezeigten negativen Temperaturen gelöst habe. Bitte einmal auf v0.51 updaten. 
Achtung wenn ihr einen anderen Pin als Pin26 nutzt dann einmal in der u-boot/config.txt nach der installation anpassen.

I think that with version 0.51 I have solved the problem with the negative temperatures not being displayed. Please update to v0.51.
Attention, if you use a pin other than Pin26 then adjust it in u-boot/config.txt after installation.

Release v0.51 -> https://github.com/Rikkert-RS/VenusOS-TemperatureService/releases/tag/v0.51

best regards Rikkert-RS

**Comment by T-Minberg** [comment]
Konnte es leider wegen Krankheit noch nicht ausprobieren. ( Venus OS läuft im Wohnmobil) lch werde es ausprobieren sobald ich es wieder kann. Da ich eine Relaiskarte auf meinem Rpi3 habe muss ich schauen auf welchem Pin ich die Sensoren habe. 
Vielen Dank für deine Hilfe 👍👍
