### ISSUE TITLE
Temperatures freezing when inactive

### ISSUE THREAD

**Issue by Fraser86** [Rikkert-RS/VenusOS-TemperatureService#4]
Ok Rikkert, 
So i have run into an issue which I wanna share. 
I have been doing some testing with 3 temperature sensors. 
My pi is next to fridge freezer so i put one in fridge, one in the freezer and one is hanging in the kitchen. 

This all works and shows me the temperature. 

However after a while i take them out but the temps are all sticking and not adjusting to room temp. 

After rebooting the temps are displayed correctly.

**Comment by Rikkert-RS** [comment]
Hello Fraser86,

I just found time to solve the problem.

There was an error reading the temperature value. This is fixed in version 0.5
https://github.com/Rikkert-RS/VenusOS-TemperatureService/releases/tag/latest

**Comment by Rikkert-RS** [comment]
**Attention** completely forgotten. 
Please uninstall version v0.4 in the setup first before installing version 0.5 
because the GPIO PIN has been changed from **4 to 26**
