### ISSUE TITLE
Two or more DS18B20 temp sensors 

### ISSUE THREAD

**Issue by twaldenmeier** [Rikkert-RS/VenusOS-TemperatureService#7]
Can I add two or more DS18B20 temp sensors and they will show up on the console?

**Comment by Rikkert-RS** [comment]
Hello, yes it is a Bus system

look at this Post: 
https://github.com/Rikkert-RS/VenusOS-TemperatureService/issues/5#issuecomment-1591694233

**Comment by twaldenmeier** [comment]
Thank you! I will give it a try!

**Comment by twaldenmeier** [comment]
I have connected a second sensor but I am not sure if I configured the config.txt correct since it does not show up on the console. The custom name disappeared and this is what it looks like with even two sensors connected

![image](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/136368866/0a00a524-057b-4138-824e-61f3311e8dbc)

This is the change I made ... second sensor isconnected to Data Pin 4 (GPIO).
![image](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/136368866/01e1bfe7-e630-4936-bfb9-d47ca7bfc70a)


Any idea what I did wrong?

**Comment by Rikkert-RS** [comment]
Yes this is wrong 1Wire is a bus system you need only 1 Pin for that.
Do you have read my links posted before? Delete the line with pin 26 in the config.txt

You have to connect the second or more Sensors in parallel to the first one. Data pin is for all Sensors GPIO 4 in your case.

![image](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/96136114/3ff26be3-acbc-4c98-9dad-209a6094baa2)

**Comment by twaldenmeier** [comment]
Thank you!

I think I did not understand what you meant in the other comment. The
pictures explains it pretty well. Since I have not done this so far - is
there a specific product to use to accomplish his? Like one of those
breakout boards? Like this: https://amzn.to/3NBeJk1

**Comment by Rikkert-RS** [comment]
There are many possibilities, wire yourself or various boards
